### ISSUE TITLE
Color Input

### ISSUE THREAD

**Issue by codewithkyle** [codewithkyle/brixi-ui#32]
**Model**
```typescript
export class ColorComponent extends HTMLElement{
    private input:HTMLInputElement;
    private label:HTMLLabelElement;
    private textInput:HTMLInputElement;

    constructor(){
        super();
        this.input = this.querySelector(`input[type="color"]`);
        this.label = this.querySelector("label");
        this.textInput = this.querySelector(`input[type="text"]`);
    }

    private handleColor:EventListener = () => {
        this.label.style.backgroundColor = this.input.value;
        this.textInput.value = this.input.value;
    }

    private handleTextColor:EventListener = () => {
        const value = `${this.textInput.value.replace("#", "")}`;
        this.input.value = `#${value}`;
        this.label.style.backgroundColor = `#${value}`;
    }

    private focusInput:EventListener = () => {
        this.textInput.value = this.textInput.value.replace("#", "");
    }

    private blurInput:EventListener = () => {
        this.textInput.value = `#${this.textInput.value.replace("#", "")}`;
        this.input.value = this.textInput.value;
        this.label.style.backgroundColor = this.textInput.value;
    }

    connectedCallback(){
        this.input.addEventListener("change", this.handleColor);
        this.textInput.addEventListener("input", this.handleTextColor);
        this.textInput.addEventListener("focus", this.focusInput);
        this.textInput.addEventListener("blur", this.blurInput);
    }
}
```

**View**
```html
<color-component>
    <label class="sample" for="custom-background-color"></label>
    <input @change=${e => this.updateColor(e.currentTarget.value)} id="custom-background-color" type="color" />
    <div style="width:100%;flex:1;">
        <label class="label" for="custom-color-hex">Background Color</label>
        <input @blur=${e => this.updateColor(e.currentTarget.value)} type="text" value="#000000" id="custom-color-hex">
    </div>
</color-component>
```

**Stylesheet**
```scss
color-component{
    position: relative;
    display: flex;
    flex-flow: row nowrap;
    align-items: center;
    width: 100%;

    input[type="color"]{
        opacity: 0;
        visibility: hidden;
        position: absolute;
        top: 0;
        left: 0;
    }

    .sample{
        width: 55px;
        height: 55px;
        border-radius: 0.25rem;
        display: inline-block;
        box-shadow: inset 0 0 3px rgba(0,0,0,0.15);
        background-color: #000;
        cursor: pointer;
        margin-right: 1rem;
    }

    .label{
        display: block;
        width: 100%;
        font-size: var(--font-xs);
        font-weight: var(--font-medium);
        color: var(--grey-800);
        margin-bottom: 0.25rem;
    }

    input[type="text"]{
        height: 36px;
        line-height: 36px;
        padding: 0 0.5rem;
        background-color: var(--grey-100);
        border: 1px solid var(--grey-300);
        border-radius: 0.25rem;
        color: var(--grey-900);
        transition: all 150ms var(--ease-in-out);
        width: 100%;
        display: block;

        &::placeholder {
            color: var(--grey-700);
        }

        &:hover {
            border-color: var(--primary-400);
        }

        &:focus {
            border-color: var(--primary-400);
            box-shadow: 0 0 0 5px var(--primary-100);
            background-color: var(--white);
        }
    }
}
```
